language: node_js
node_js:
  - '8'
  - '10'
  - '11'
  - '12'
dist: trusty
sudo: false
cache: yarn
addons:
  chrome: stable

services:
  - docker

matrix:
  allow_failures:
    - node_js: '12'
  fast_finish: true

# add the current github branch as an environment variable
before_script:
  - export REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
  - export NODE_OPTIONS=--max_old_space_size=4096
script:
  - npm run build
  - docker run -i wallies/nodejsscan-cli -d ./src -o ./results.json | cat ./results.json | python -m json.tool

# install firebase cli and set firebase project ci token from environment
before_deploy:
  - npm install -g firebase-tools
  - export FIREBASE_TOKEN=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "$FIREBASE_PRODUCTION_TOKEN"; else echo "$FIREBASE_STAGING_TOKEN"; fi)
deploy:
  - provider: script
    script: bash scripts/deploy.dev.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.sh
    skip_cleanup: true
    on:
      branch: production
  - provider: script
    script: bash scripts/deploy.notification.sh
    on:
      all_branches: true
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
  - docker run -u zap -i owasp/zap2docker-stable zap-cli quick-scan -sc -o '-config api.disablekey=true' -s xss,sqli --spider "https://dev.onearmy.world"
